name: CI-CD workflows
on:
    push:
        branches:
            main
jobs:
    test-job:
        runs-on: ubuntu-latest    
        steps:
            - name: checkout-code
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: "3.10"
            - name: Install Depencies
              run: pip install -r requirements.txt
            - name: run test cases
              run: pytest --cov=calc --cov-report=term
    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job
        steps:
            - name: print message
              run : echo "deploy job started..."        